# Dependencies
# markdown:         redcarpet
markdown: kramdown
# highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title: Â¥One
email: your-email@example.com
tagline:          'A Jekyll theme'
description: >- # this means to ignore newlines until "baseurl:"
  <a href="https://github.com/soarcreator">soarcreator</a>
url: https://soarcreator.github.io/
baseurl: /

author:
  name:           'soarcreator'
  url:            https://twitter.com/soarcreator

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/soarcreator
